In [3]:
def MM(a,b):
    c = []
    for i in range(0,len(a)):
        temp=[]
        for j in range(0,len(b[0])):
            s = 0
            for k in range(0,len(a[0])):
                s += a[i][k]*b[k][j]
            temp.append(s)
        c.append(temp)
    return c

a=[[1,2]]
b=[[1],[2]]
print(MM(a,b))

[[5]]


In [4]:
import numpy as np

In [15]:
N = 10
A = np.array([[0]*N]*N)
for i in range(N):
    A[i, i] = 1

for i in range(N-1):
    a, b = input().split(" ")
    a = int(a)
    b = int(b)
    A[a, b] = 1
    A[b, a] = 1
B = A.copy()

1 8
3 4
8 3
2 3
2 6
7 6
5 6
5 9
6 0


In [37]:
a = 1
B = np.dot(A, A)
trouve = False
origins = []
while not trouve:
    for i in range(N):
        if sum(B[i] == 0) <= 0:
            print(i)
            trouve = True
            origins.append(i)
    a += 1
    B = np.dot(B, A)
print(a)
print(B)

2
3
[[11  0 11  4  1 11 20 10  1  4]
 [ 0  9  4 10  4  0  1  0 12  0]
 [11  4 22 20 10 12 24 11 11  4]
 [ 4 10 20 30 16  4 13  4 20  1]
 [ 1  4 10 16 10  1  4  1 10  0]
 [11  0 12  4  1 20 24 11  1 12]
 [20  1 24 13  4 24 43 20  4 11]
 [10  0 11  4  1 11 20 11  1  4]
 [ 1 12 11 20 10  1  4  1 19  0]
 [ 4  0  4  1  0 12 11  4  0  9]]


In [38]:
origins

[2]

In [ ]:
for i in range(3):
    B = np.dot(B, B)

print(B)

In [24]:
C = A.copy()
C

array([[0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 1, 0, 0, 1, 0, 0, 0],
       [0, 0, 1, 0, 1, 0, 0, 0, 1, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 1],
       [1, 0, 1, 0, 0, 1, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 1, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0]])

In [19]:
a = 1
B = MM(A, A)
trouve = False
while not trouve:
    for i in range(N):
        if sum(B[i] == 0) <= 0:
            print(i)
            trouve = True
            break
    a += 1
    B = MM(A, A)
print(a)
print(B)

TypeError: 'bool' object is not iterable

In [22]:
D = [list(i) for i in A]
D

[[1, 0, 0, 0, 0, 0, 1, 0, 0, 0],
 [0, 1, 0, 0, 0, 0, 0, 0, 1, 0],
 [0, 0, 1, 1, 0, 0, 1, 0, 0, 0],
 [0, 0, 1, 1, 1, 0, 0, 0, 1, 0],
 [0, 0, 0, 1, 1, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 1, 1, 0, 0, 1],
 [1, 0, 1, 0, 0, 1, 1, 1, 0, 0],
 [0, 0, 0, 0, 0, 0, 1, 1, 0, 0],
 [0, 1, 0, 1, 0, 0, 0, 0, 1, 0],
 [0, 0, 0, 0, 0, 1, 0, 0, 0, 1]]

In [31]:
for i in range(N):
    A[i, i] = 1

In [32]:
B

array([[ 2920802608108563130,                    0,  1351912868111925223,
                           0, -1568889739996637907, -2708873485185658070,
                           0,  2920802608108563130, -8932939547727482627,
                           0],
       [                   0, -8327375632310129379,                    0,
         6224066062541824557,                    0,                    0,
        -8932939547727482627,                    0,                    0,
        -7021907912681123603],
       [ 1351912868111925223,                    0,  4272715476220488353,
                           0,  2920802608108563130,  6804931040796410919,
                           0,  1351912868111925223, -2708873485185658070,
                           0],
       [                   0,  6224066062541824557,                    0,
        -4812183054953962892,                    0,                    0,
        -9149916419612195311,                    0,                    0,
        -8932939547